env:
  global:
    - SHELLCHECK_OPTS=""
matrix:
  include:
    - language: bash
      script:
        - shellcheck --version
        - bash -c 'shopt -s globstar nullglob; shellcheck --format=gcc ./packer-templates/**/*.{sh,ksh,bash}'
